name: Alex Weiss
favicon: null
layout_spectrum: 0.76573
typography_spectrum: 0.45936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#373737'
    - '#007fc6'
    - '#60a5e6'
    - '#bd6363'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
