name: Alex Weiss Portfolio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#3b393a'
    - '#bebdbb'
    - '#a39a93'
    - '#9b794c'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
