name: Alex Weiss Portfolio
favicon: null
layout_spectrum: 0.0939727642107755
typography_spectrum: 0.32162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#3b393a'
    - '#bebdbb'
    - '#a39a93'
    - '#9b794c'
  brandStrength: 0.40647998452186584
  lightness: 0.6077849064022303
  saturation: 0.946207603206858
  rhythmicContrast: 0.03655761480331421
purpose: []
